# Generated by Django 3.1.3 on 2020-11-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0011_auto_20201126_1348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consult_tbl',
            options={'permissions': [('can_view_consult', 'Can View Consult')]},
        ),
        migrations.AddField(
            model_name='consult_tbl',
            name='cu_student',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
