# Generated by Django 3.1.3 on 2020-11-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0012_auto_20201130_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consult_tbl',
            name='cu_res_time',
            field=models.DateTimeField(null=True),
        ),
    ]
