# Generated by Django 3.1.3 on 2020-12-01 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0013_auto_20201130_1145'),
        ('admin', '0015_auto_20201127_1514'),
    ]

    operations = [
    ]
