# Generated by Django 3.1.3 on 2020-12-01 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_auto_20201124_1640'),
        ('signup', '0004_auto_20201123_2257'),
    ]

    operations = [
    ]
